### ISSUE TITLE
How to make Dump Channel

### ISSUE THREAD

**Issue by charindithjaindu** [No-OnE-Kn0wS-Me/TG-URL-Uploader#1]
How can we make a dump channel to view what are the other users uploading

just forwarding what they uploaded

**Comment by Senpai-sama-afk** [comment]
Next level of spying, you sound like Whatsapp CEO
event.forward(dump_channel_id)
The rest figure it out

**Comment by charindithjaindu** [comment]
> Next level of spying, you sound like Whatsapp CEO
> event.forward(dump_channel_id)
> The rest figure it out

lol😁😂, anyway thanks for the help

**Comment by Senpai-sama-afk** [comment]
Yeah, don't be like Mark XD
